# This role installs and sets up Ganglia Performance Monitoring with
# Web Interface for CENTRAL VM.
# As we have internal network I've decided to use unicast for comms.
# This role also sets up RabbitMQ Ganglia monitoring, using scripts from
# official repository of user-contributed Gmond Python DSO modules.
# (https://github.com/ganglia/gmond_python_modules)
#
- name: Install Ganglia
  yum:
    name: ganglia, ganglia-gmetad, ganglia-gmond, ganglia-web, ganglia-gmond-python
    state: present
- name: Configure gmetad cluster name
  replace:
    path: /etc/ganglia/gmetad.conf
    regexp: 'data_source\ "my\ cluster"\ localhost'
    replace: 'data_source "urbunny" central'
- name: Configure gmond unicast - 1
  replace:
    path: /etc/ganglia/gmond.conf
    regexp: 'mcast_join\ =\ 239\.2\.11\.71'
    replace: '#mcast_join = 239.2.11.71'
- name: Configure gmond unicast - 2
  replace:
    path: /etc/ganglia/gmond.conf
    regexp: 'bind\ =\ 239\.2\.11\.71'
    replace: '#bind = 239.2.11.71'
- name: Configure gmond send channel
  lineinfile:
    path: /etc/ganglia/gmond.conf
    insertafter : 'udp_send_channel\ \{'
    line: 'host = central'
    state: present
- name: Configure htpasswd
  shell: /usr/bin/htpasswd -bc /etc/httpd/auth.basic admin admin
- name: Configure httpd
  copy:
    src: ganglia.conf
    dest: /etc/httpd/conf.d/ganglia.conf
- name: Install Ganglia RabbitMQ python monitoring script
  copy:
    src: rabbitmq.py
    dest: /usr/lib64/ganglia/python_modules/rabbitmq.py
- name:  Install Ganglia RabbitMQ python monitoring script configuration
  copy:
    src: rabbitmq.pyconf
    dest: /etc/ganglia/conf.d/rabbitmq.pyconf
