
---

### Nagios Variables ###
nagios_username: nagiosadmin
nagios_password: changeme
nagios_create_guest_user: true
nagios_ro_username: guest
nagios_ro_password: guest
nagios_http_port: 80
nagios_https_port: 443
admin_name_01: nagiosadmin
# change this to your email address if you want notifications
admin_email_01: nagios@localhost
### NRPE variables ###
nrpe_tcp_port: 5666
# threshold for # of processes
warning_proc: 900
critical_proc: 1000
# threshold for # of logged in users
warning_users: 15
critical_users: 30
### ELK options ###
# if you use my ELK playbook you'll need this for HTTP checks
# https://github.com/sadsfae/ansible-elk
kibana_user: admin
kibana_password: admin
### snmp options ###
# these are for dell idrac only
snmp_mib_path: /usr/share/snmp/mibs
snmp_opts: -v2c -c public
# these flag for strings to match failure, warn or ok
snmp_check_thresholds: --warn '$ALL$' --crit 'critical|nonRecoverable|fail' --ok 'ok|online|on|spunup|full|ready|enabled|unknown|presence'
# settings to check for idrac
# power supply
idrac_ps: true
# system fans and speed
idrac_fan: true
# CMOS battery
idrac_battery: true
# power redundancy
idrac_pu: true
# system memory
idrac_mem: true
# physical disk/RAID
idrac_disk: true
# RAID vdisk or JBOD
idrac_vdisk: true
# temperature
idrac_sensor: true
# system cpu
idrac_cpu: true
