- name: Install Java
  yum:
    name: java, java-devel
    state: present
- name: Create App directory
  file:
    path: /opt/urbunny
    state: directory
- name: Install Send.java
  copy:
    src: Send.java
    dest: /opt/urbunny/Send.java
- name: Install libraries - amqp-client
  copy:
    src: amqp-client-4.0.2.jar
    dest: /opt/urbunny/amqp-client-4.0.2.jar
- name: Install libraries - slf4j-api
  copy:
    src: slf4j-api-1.7.21.jar
    dest: /opt/urbunny/slf4j-api-1.7.21.jar
- name: Install libraries - slf4j-simple
  copy:
    src: slf4j-simple-1.7.22.jar
    dest: /opt/urbunny/slf4j-simple-1.7.22.jar
- name: Compile Application
  shell: cd /opt/urbunny && /usr/bin/javac -cp amqp-client-4.0.2.jar Send.java
- name: Install QSend.sh
  copy:
    src: QSend.sh
    dest: /opt/urbunny/QSend.sh
    mode: 0755
- name: Install QClog.sh
  copy:
    src: QClog.sh
    dest: /opt/urbunny/QClog.sh
    mode: 0755
- name: Put some numbers in queue (see Description for details)
  command: /opt/urbunny/QClog.sh 10
  when: queue_warmup = 1