# This role installs simple Python App with lib to consume messages
# from our queue and sleep 'message payload' seconds as per
# requirements. Receiver installs as systemd service and restarts
# in case of failure. See README for known issues!
# You can run as many receivers as you'd like in parallel.
# As it's the first role to run we also copy /etc/hosts with it.
#
- name: Copy system hosts file
  copy:
    src: hosts
    dest: /etc/hosts
- name: Install pika
  yum:
    name: python2-pika
    state: present
- name: Create App directory
  file:
    path: /opt/urbunny
    state: directory
- name: Install receiver.py
  copy:
    src: receiver.py
    dest: /opt/urbunny/receiver.py
    mode: 0755
- name: Install systemd configuration
  copy:
    src: urbunny-receiver.service
    dest: /etc/systemd/system/urbunny-receiver.service
- name: Reload systemd
  shell: systemctl daemon-reload
