---
- hosts: central
  remote_user: root
  tasks:
  - name: Central OS - install RabbitMQ
    yum:
      name: rabbitmq-server
      state: present
  - name: Central RabbitMQ - reverse dns lookup
    replace:
      path: /etc/rabbitmq/rabbitmq.config
      regexp: '%%\ \{reverse_dns_lookups,\ true\},'
      replace: '{reverse_dns_lookups, false},'
  - name: Central RabbitMQ - guest connect
    replace:
      path: /etc/rabbitmq/rabbitmq.config
      regexp: '%%\ \{loopback_users,\ \[\]\},'
      replace: '{loopback_users, []}'
  - name: Central OS - RabbitMQ enable
    service:
      name: rabbitmq-server
      state: started
      enabled: yes
  - name: Central OS - Java install
    yum:
      name: java
      state: present
  - name: Central App - mkdir
    file:
      path: /opt/urbunny
      state: directory
  - name: Central App - install Send.java
    copy:
      src: /etc/ansible/apps/writer/Send.java
      dest: /opt/urbunny/Send.java
  - name: Central App - install amqp-client
    copy:
      src: /etc/ansible/apps/writer/amqp-client-4.0.2.jar
      dest: /opt/urbunny/amqp-client-4.0.2.jar
  - name: Central App - install slf4j-api
    copy:
      src: /etc/ansible/apps/writer/slf4j-api-1.7.21.jar
      dest: /opt/urbunny/slf4j-api-1.7.21.jar
  - name: Central App - install slf4j-simple
    copy:
      src: /etc/ansible/apps/writer/slf4j-simple-1.7.22.jar
      dest: /opt/urbunny/slf4j-simple-1.7.22.jar
  - name: Central App - install QClog.sh
    copy:
      src: /etc/ansible/apps/writer/QClog.sh
      dest: /opt/urbunny/QClog.sh
      mode: 0755

- hosts: workers
  remote_user: root
  tasks:
  - name: Worker OS - /etc/hosts
    lineinfile: dest=/etc/hosts
                insertafter=EOF
                state=present
                regexp='^172\.16\.16\.11'
                line='172.16.16.11 CENTRAL CENTRAL'
  - name: Worker OS - install pika
    yum:
      name: python2-pika
      state: present
  - name: Worker App - mkdir
    file:
      path: /opt/urbunny
      state: directory
  - name: Worker App - receiver.py
    copy:
      src: /etc/ansible/apps/reader/receiver.py
      dest: /opt/urbunny/receiver.py
  - name: Worker App - systemd config
    copy:
      src: /etc/ansible/apps/reader/urbunny-receiver.service
      dest: /etc/systemd/system/urbunny-receiver.service
  - name: Worker App install - systemd reload
    shell: systemctl daemon-reload
  - name: Worker App - service enable
    service:
      name: urbunny-receiver
      state: started
      enabled: yes
...
