---
- hosts: workers
  remote_user: root
  tasks:
  - name: /etc/hosts update workers
    lineinfile: dest=/etc/hosts
                insertafter=EOF
                line='172.16.16.11 CENTRAL CENTRAL'
...

