---

hosts: all
	- name disable SELinux (just in case)
	command /sbin/setenforce 0

	- name /etc/hosts update central
	- lineinfile:
	path: /etc/hosts
	insertafter: EOF
	line: '172.16.16.11 CENTRAL CENTRAL'

	- name /etc/hosts update worker
	- lineinfile:
	path: /etc/hosts
	insertafter: EOF
	line: '172.16.16.21 WORKER WORKER'
