---
- hosts: central
  roles:
    - rabbitmq-server
    - central-app
    - nagios
  remote_user: root
  - name: Central OS - RabbitMQ enable
    service:
      name: rabbitmq-server
      state: started
      enabled: yes
  - name: Central Nagios - RabbitMQ monitoring script
     copy:
      src: /etc/ansible/apps/nagios/rabbit.sh
      dest: /usr/lib64/nagios/rabbit.sh
      mode: 0755
  - name: Central Nagios - sudoers setup
     copy:
      src: /etc/ansible/apps/nagios/nagios
      dest: /etc/sudoers.d/nagios
  - name: Central Ganglia - gmetad enable
    service:
      name: gmetad
      state: started
      enabled: yes
  - name: Central Ganglia - gmond enable
    service:
      name: gmond
      state: started
      enabled: yes
  - name: Central Ganglia - httpd enable
    service:
      name: httpd
      state: started
      enabled: yes

- hosts: workers
  remote_user: root
  tasks:
  - name: Worker OS - hosts file
    copy:
      src: /etc/ansible/apps/hosts
      dest: /etc/hosts
  - name: Worker OS - install pika
    yum:
      name: python2-pika
      state: present
  - name: Worker App - mkdir
    file:
      path: /opt/urbunny
      state: directory
  - name: Worker App - receiver.py
    copy:
      src: /etc/ansible/apps/reader/receiver.py
      dest: /opt/urbunny/receiver.py
      mode: 0755
  - name: Worker App - systemd config
    copy:
      src: /etc/ansible/apps/reader/urbunny-receiver.service
      dest: /etc/systemd/system/urbunny-receiver.service
  - name: Worker App install - systemd reload
    shell: systemctl daemon-reload
  - name: Worker App - service enable
    service:
      name: urbunny-receiver
      state: started
      enabled: yes
  - name: Worker Ganglia - install
    yum:
      name: ganglia, ganglia-gmond
      state: present
  - name: Worker Ganglia - config gmond unicast
    replace:
      path: /etc/ganglia/gmond.conf
      regexp: 'mcast_join\ =\ 239\.2\.11\.71'
      replace: '#mcast_join = 239.2.11.71'
  - name: Worker Ganglia - config gmond unicast2
    replace:
      path: /etc/ganglia/gmond.conf
      regexp: 'bind\ =\ 239\.2\.11\.71'
      replace: '#bind = 239.2.11.71'
  - name: Worker Ganglia - config gmond receive
    lineinfile:
      path: /etc/ganglia/gmond.conf
      insertafter : 'udp_send_channel\ \{'
      line: 'host = central'
      state: present
  - name: Central Ganglia - gmond enable
    service:
      name: gmond
      state: started
      enabled: yes
...
