---
- hosts: central
  remote_user: root
  tasks:
  - name: Central OS - install RabbitMQ
    yum:
      name: rabbitmq-server
      state: present
  - name: Central RabbitMQ - reverse dns lookup
    replace:
      path: /etc/rabbitmq/rabbitmq.config
      regexp: '%%\ \{reverse_dns_lookups,\ true\},'
      replace: '{reverse_dns_lookups, false},'
  - name: Central RabbitMQ - guest connect
    replace:
      path: /etc/rabbitmq/rabbitmq.config
      regexp: '%%\ \{loopback_users,\ \[\]\},'
      replace: '{loopback_users, []}'
  - name: Central OS - RabbitMQ enable
    service:
      name: rabbitmq-server
      state: started
      enabled: yes
  - name: Central OS - Java install
    yum:
      name: java, java-devel
      state: present
  - name: Central App - mkdir
    file:
      path: /opt/urbunny
      state: directory
  - name: Central App - install Send.java
    copy:
      src: /etc/ansible/apps/writer/Send.java
      dest: /opt/urbunny/Send.java
  - name: Central App - install amqp-client
    copy:
      src: /etc/ansible/apps/writer/amqp-client-4.0.2.jar
      dest: /opt/urbunny/amqp-client-4.0.2.jar
  - name: Central App - install slf4j-api
    copy:
      src: /etc/ansible/apps/writer/slf4j-api-1.7.21.jar
      dest: /opt/urbunny/slf4j-api-1.7.21.jar
  - name: Central App - install slf4j-simple
    copy:
      src: /etc/ansible/apps/writer/slf4j-simple-1.7.22.jar
      dest: /opt/urbunny/slf4j-simple-1.7.22.jar
  - name: Central App - compile
    shell: cd /opt/urbunny && /usr/bin/javac -cp amqp-client-4.0.2.jar Send.java
  - name: Central App - install QClog.sh
    copy:
      src: /etc/ansible/apps/writer/QSend.sh
      dest: /opt/urbunny/QSend.sh
      mode: 0755
  - name: Central App - install QClog.sh
    copy:
      src: /etc/ansible/apps/writer/QClog.sh
      dest: /opt/urbunny/QClog.sh
      mode: 0755
  - name: Central OS - install Zabbix Server
    yum:
      name: zabbix22-server-mysql, zabbix22-web-mysql, mariadb-server
      state: present
  - name: Central Zabbix - start MariaDB
    service:
      name: mariadb
      state: started
      enabled: yes
  - name: Central Zabbix - DB initial setup
    shell: /usr/bin/mysql -uroot < /etc/ansible/apps/zabbix/zabbix1.sql
    args:
      creates: /etc/zabbix/db_setup_complete
  - name: Central Zabbix - DB schema setup
    shell: /usr/bin/mysql -uroot zabbix < /usr/share/zabbix-mysql/schema.sql
    args:
      creates: /etc/zabbix/db_setup_complete
  - name: Central Zabbix - DB images setup
    shell: /usr/bin/mysql -uroot zabbix < /usr/share/zabbix-mysql/images.sql
    args:
      creates: /etc/zabbix/db_setup_complete 
  - name: Central Zabbix - DB data setup
    shell: /usr/bin/mysql -uroot zabbix < /usr/share/zabbix-mysql/data.sql
    args:
      creates: /etc/zabbix/db_setup_complete
  - name: Central Zabbix - really dumb way to mark DB data setup completion
    file:
      path: /etc/zabbix/db_setup_complete
      state: touch
  - name: Central Zabbix - DBHost
    replace:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '#\ DBHost=localhost'
      replace: 'DBHost=localhost'
  - name: Central Zabbix - DBPassword
    replace:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '#\ DBPassword='
      replace: 'DBPassword=zabbix'
  - name: Central Zabbix - start zabbix-server
    service:
      name: zabbix-server-mysql
      state: started
      enabled: yes
  - name: Central Zabbix - php post_max_size
    replace:
      path: /etc/php.ini
      regexp: 'post_max_size\ =\ 8M'
      replace: 'post_max_size = 16M'
  - name: Central Zabbix - php max_execution_time
    replace:
      path: /etc/php.ini
      regexp: 'max_execution_time\ =\ 30'
      replace: 'max_execution_time = 300'
  - name: Central Zabbix - php max_input_time
    replace:
      path: /etc/php.ini
      regexp: 'max_input_time\ =\ 60'
      replace: 'max_input_time = 300'
  - name: Central Zabbix - php max_input_time
    replace:
      path: /etc/php.ini
      regexp: ';date.timezone\ ='
      replace: 'date.timezone = Europe/Riga'
  - name: Central Zabbix - start httpd
    service:
      name: httpd
      state: started
      enabled: yes

- hosts: workers
  remote_user: root
  tasks:
  - name: Worker OS - /etc/hosts
    lineinfile: dest=/etc/hosts
                insertafter=EOF
                state=present
                regexp='^172\.16\.16\.11'
                line='172.16.16.11 CENTRAL CENTRAL'
  - name: Worker OS - install pika
    yum:
      name: python2-pika
      state: present
  - name: Worker App - mkdir
    file:
      path: /opt/urbunny
      state: directory
  - name: Worker App - receiver.py
    copy:
      src: /etc/ansible/apps/reader/receiver.py
      dest: /opt/urbunny/receiver.py
      mode: 0755
  - name: Worker App - systemd config
    copy:
      src: /etc/ansible/apps/reader/urbunny-receiver.service
      dest: /etc/systemd/system/urbunny-receiver.service
  - name: Worker App install - systemd reload
    shell: systemctl daemon-reload
  - name: Worker App - service enable
    service:
      name: urbunny-receiver
      state: started
      enabled: yes
...
