---
- hosts: central
  remote_user: root
  roles:
    - rabbitmq-server
    - central-app
    - ganglia-central
    - nagios
  tasks:
  - name: enable RabbitMQ
    service:
      name: rabbitmq-server
      state: started
      enabled: yes
  - name: Ganglia - gmetad enable
    service:
      name: gmetad
      state: started
      enabled: yes
  - name: Ganglia - gmond enable
    service:
      name: gmond
      state: started
      enabled: yes
  - name: Ganglia - httpd enable
    service:
      name: httpd
      state: started
      enabled: yes

- hosts: workers
  remote_user: root
  roles:
    - worker-app
    - ganglia-worker
  tasks:
  - name: Enable Ganglia gmond
  service:
    name: gmond
    state: started
    enabled: yes
...
