---
- hosts: all
  remote_user: root
  tasks:
  - name: disable SELinux
    command: /sbin/setenforce 0

  - name: /etc/hosts update central
    lineinfile: dest=/etc/hosts
                insertafter=EOF
                line='172.16.16.11 CENTRAL CENTRAL'
  - name: /etc/hosts update worker
    lineinfile: dest=/etc/hosts
                insertafter=EOF
                line='172.16.16.21 WORKER WORKER'
...

