---
- hosts: workers
  remote_user: root
  tasks:
  - name: /etc/hosts update workers
    lineinfile: dest=/etc/hosts
                insertafter=EOF
                state=present
                regexp='^172\.16\.16\.11'
                line='172.16.16.11 CENTRAL CENTRAL'
- hosts: central
  remote_user: root
  tasks:
  - name: install RabbitMQ AMQP
    yum:
      name: rabbitmq-server
      state: present
  - name: config RabbitMQ - reverse dns lookup
    replace:
      path: /etc/rabbitmq/rabbitmq.config
      regexp: '(\s+)%%\{reverse_dns_lookups\,\ false\}\,'
      replace: '(\s+)\{reverse_dns_lookups\,\ false\}\,'
  - name: config RabbitMQ - guest connect
    replace:
      path: /etc/rabbitmq/rabbitmq.config
      regexp: '(\s+)%%\{loopback_users\,\ \[\]\}\,'
      replace: '(\s+)\{loopback_users\,\ \[\]\}'
  - name: enable RabbitMQ
    service:
      name: rabbitmq-server
      state: started
      enabled: yes
...
