# This role installs from repo and starts RabbitMQ server on CENTRAL VM.
# I disabled reverse_dns_lookup "just in case" and
# allowed unauthenticated guest access as per requirements.
# We also have to enable RabbitMQ Management API to make Ganglia queue 
# monitoring work.
# We put /etc/hosts file here as it's first role to run and just a file copy
# doesn't look suitable for a standalone role to me.
#
- name: Copy system hosts file
  copy:
    src: hosts
    dest: /etc/hosts
- name: Install RabbitMQ
  yum:
    name: rabbitmq-server
    state: present
- name: Configure RabbitMQ - reverse dns lookup
  replace:
    path: /etc/rabbitmq/rabbitmq.config
    regexp: '%%\ \{reverse_dns_lookups,\ true\},'
    replace: '{reverse_dns_lookups, false},'
- name: Configure RabbitMQ - guest connect
  replace:
    path: /etc/rabbitmq/rabbitmq.config
    regexp: '%%\ \{loopback_users,\ \[\]\},'
    replace: '{loopback_users, []}'
- name: Configure RabbitMQ - management API enable
  shell: /usr/sbin/rabbitmq-plugins enable rabbitmq_management
- name: Enable RabbitMQ
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
    