# This role installs and sets up Ganglia gmond
# WORKER* hosts. Nothing special.
#
- name: Install Ganglia
  yum:
    name: ganglia, ganglia-gmond
    state: present
- name: Configure gmond unicast - 1
  replace:
    path: /etc/ganglia/gmond.conf
    regexp: 'mcast_join\ =\ 239\.2\.11\.71'
    replace: '#mcast_join = 239.2.11.71'
- name: Configure gmond unicast - 2
  replace:
    path: /etc/ganglia/gmond.conf
    regexp: 'bind\ =\ 239\.2\.11\.71'
    replace: '#bind = 239.2.11.71'
- name: Configure gmond send channel
  lineinfile:
    path: /etc/ganglia/gmond.conf
    insertafter : 'udp_send_channel\ \{'
    line: 'host = central'
    state: present
