- name: Worker Ganglia - install
  yum:
    name: ganglia, ganglia-gmond
    state: present
- name: Worker Ganglia - config gmond unicast
  replace:
    path: /etc/ganglia/gmond.conf
    regexp: 'mcast_join\ =\ 239\.2\.11\.71'
    replace: '#mcast_join = 239.2.11.71'
- name: Worker Ganglia - config gmond unicast2
  replace:
    path: /etc/ganglia/gmond.conf
    regexp: 'bind\ =\ 239\.2\.11\.71'
    replace: '#bind = 239.2.11.71'
- name: Worker Ganglia - config gmond receive
  lineinfile:
    path: /etc/ganglia/gmond.conf
    insertafter : 'udp_send_channel\ \{'
    line: 'host = central'
    state: present
- name: Central Ganglia - gmond enable
  service:
    name: gmond
    state: started
    enabled: yes
